# Generated by Django 4.1.3 on 2023-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('name', models.CharField(max_length=225)),
                ('descraption', models.CharField(max_length=225)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_stock', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('price', models.SmallIntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
