# Generated by Django 4.1.3 on 2023-01-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_stock',
            field=models.BooleanField(),
        ),
    ]
